### ISSUE TITLE
Populate MacRobert Graph

### ISSUE THREAD

**Issue by KlaraKramer** [zsoltkebel/atroom-website#47]
##Create the graph object for MacRobert##
On the atroom.at account atroom@at.room, 12345678
Aysha: Ground floor
Ben: First floor
Claire: Third floor + Fourth floor
Zsolt: Fifth floor

**Please ensure all nodes have the right type (door, junction, stairs etc.), and that floors are connected appropriately**

**Comment by zsoltkebel** [comment]
Hey, I got started on floor 5. Let me know if you get stuck using the website or if there are any errors as I understand that the current version might have bugs or not have the most intuitive UI.
